#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
$env = is_file(__DIR__ . '/../config/env.php') ? require(__DIR__ . '/../config/env.php') : 'local';

defined('YII_DEBUG') or define('YII_DEBUG', $env !== 'prod');
defined('YII_ENV') or define('YII_ENV', $env);
defined('YII_ENV_LOCAL') or define('YII_ENV_LOCAL', YII_ENV === 'local');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
Yii::setAlias('@app', __DIR__);

$config = is_file(__DIR__ . '/runtime/console.php') ? require(__DIR__ . '/runtime/console.php') : require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
